### PR TITLE
Update SciJava and TensorFlow

### PR DESCRIPTION
**Pull request by hadim**
Last TF version is 1.8.0. I would like to upgrade it here before the next Fiji release.

### CODE REVIEW

**Comment by imagejan** [comment]
Is there a reason why we need to override the version here, and not just update `pom-scijava` to include the newest version?
Currently, `pom-scijava` defines 1.6.0 here:

https://github.com/scijava/pom-scijava/blob/2d56ae4b3e3c898c4d95ad16226c56825edd0377/pom.xml#L830-L831

If that one gets updated, we could remove the override here.

**Comment by hadim** [comment]
I didn't realize it was an override and already defined into `pom-scijava`. So I guess that override should just be removed and `pom-scjiava` updated to 1.8.0?

**Comment by ctrueden** [comment]
Need to add regression tests to [fiji/microscope-image-quality](https://github.com/fiji/microscope-image-quality) that ensure results do not change. Then we can verify that 1.6 ➡️  1.8 is safe. Don't want to upgrade before doing that.

**Comment by ctrueden** [comment]
@hadim Did you get impatient? :wink: I still think we should update TensorFlow. And we are about to break backwards compatibility in fiji/microscope-image-quality anyway (see fiji/microscope-image-quality#5), which means this is a perfect time to do the 1.6 -> 1.8 upgrade as well.

**Pull request closed without merging**
