### PR TITLE
Cache folder

### PR DESCRIPTION
**Pull request by hadim**
Ping @frauzufall.

Can you push your commits in this PR (you should be able to directly push in my branch `hadim/cache-folder`).

### CODE REVIEW

**Comment by frauzufall** [comment]
@hadim sorry for ignoring this for a year.. I added my changes and cleaned up the commits (I removed the pom-scijava update and the code style changes for now), After merging https://github.com/imagej/imagej-tensorflow/pull/18 I will force-push a rebased version to your branch here if you don't mind and then we can merge it.

**Comment by frauzufall** [comment]
In case we are still fine with the system variable `imagej.models.dir`, I would merge this. I tested it by setting the variable in IntelliJ and behaved as expected.

**Comment by ctrueden** [comment]
We might want `tensorflow` in the property name somewhere, because other frameworks might need their own models directories. Or I suppose we could always take care in future for each library to double check that a given models directory matches its expectations?

**Comment by frauzufall** [comment]
How about `imagej.tensorflow.models.dir`? In a future PR, we could also introduce `imagej.tensorflow.downloads.dir` to save the downloaded TF versions to.. And make these paths configurable in the `Edit > Options > Tensorflow..` plugin....

**Comment by frauzufall** [comment]
I made a new issue for the related improvements I mentioned: https://github.com/imagej/imagej-tensorflow/issues/22

**Pull request merged**
