### PR TITLE
Changes to Tensors API

### PR DESCRIPTION
**Pull request by HedgehogCode**
See my last commit message for a description of the API and explanations for some design decisions.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks for your efforts on this, @HedgehogCode! The code is looking much better thanks to your improvements!

Note that it is best practice to never merge WIPs to master. The point of writing "WIP" is to signify that the commit is _not_ ready for merge, and is rather intended to be rewritten via git rebase. As such, I have squashed all the commits into a single one which makes all the changes. It is a little bit of a monster, and would be better if we split it up into chunks. Every commit in the history needs to compile with passing tests, though.

Relatedly: there are no unit tests for the `Tensors` class. It would be awesome if you had time to write some. It is important to be certain that these methods work the way you intend them to, and that we have a safety net in place to catch regressions should the code change again in the future.

**Review by ctrueden — CHANGES_REQUESTED** [review]
Please add unit tests for the `Tensors` class. This will be a file `src/test/java/net/imagej/tensorflow/TensorsTest.java` which uses JUnit. See the ImageJ Ops project for many examples.

**Comment by HedgehogCode** [comment]
Your rebase doesn't contain my latest commit but I have already updated my local branch. Is there any way to recover the commit or the old branch?

**Comment by HedgehogCode** [comment]
I figured it out. GIT is awesome!

**Review by ctrueden — APPROVED** [review]

**Comment by ctrueden** [comment]
👍 👍 🍻 👍 🥇

**Pull request merged**
